package com.assetiq.assets;

import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;

import java.util.UUID;

/**
 * Hands out asset-tag numbers, one counter per organisation and prefix (V54).
 *
 * <p>Tags used to be generated by reading every existing {@code PREFIX-*} tag and
 * adding one. Two saves that overlapped read the same highest number and built
 * the same tag; one of them then failed on {@code uq_asset_org_tag_live} (and
 * was reported as a duplicate <em>name</em>, which it was not). The counter row
 * is claimed with an UPDATE, so concurrent callers queue on its row lock for the
 * instant it takes and each leaves with a different number.
 */
@Component
public class AssetTagAllocator {

    private final JdbcTemplate jdbc;
    private final AssetTagCounterSeeder seeder;

    public AssetTagAllocator(JdbcTemplate jdbc, AssetTagCounterSeeder seeder) {
        this.jdbc = jdbc;
        this.seeder = seeder;
    }

    /**
     * The next number for this organisation and prefix. No two callers receive
     * the same one, whatever they do concurrently.
     *
     * @param highestExisting the highest number already used by a tag with this
     *                        prefix, used only when the counter does not exist yet
     */
    @Transactional
    public long claimNext(UUID organisationId, String prefix, long highestExisting) {
        int claimed = increment(organisationId, prefix);
        if (claimed == 0) {
            seeder.seedIfMissing(organisationId, prefix, highestExisting);
            increment(organisationId, prefix);
        }
        Long next = jdbc.queryForObject(
                "SELECT next_number FROM asset_tag_sequence WHERE organisation_id = ? AND prefix = ?",
                Long.class, organisationId, prefix);
        return next == null ? highestExisting + 1 : next;
    }

    private int increment(UUID organisationId, String prefix) {
        return jdbc.update(
                "UPDATE asset_tag_sequence SET next_number = next_number + 1 "
                        + "WHERE organisation_id = ? AND prefix = ?",
                organisationId, prefix);
    }
}
