#!/usr/bin/env bash
#
# bootstrap.sh — one command, run once, before the first `docker compose up`.
#
#   ./scripts/bootstrap.sh
#
# Generates every secret a self-hosted AssetIQ installation needs, writes them
# to .env with 0600 permissions, and generates a self-signed TLS certificate if
# none is present. It is non-interactive: everything has a safe default and
# anything site-specific is taken from flags or the environment.
#
#   --public-url URL   Public HTTPS URL (default: https://localhost)
#   --version TAG      Image tag to pin (default: read from VERSION file, else
#                      refuses — a self-hosted install must never track a
#                      moving tag)
#   --licence KEY      Offline licence key. Optional; without one the
#                      installation runs on free-tier quotas and can be
#                      licensed later by editing .env.
#   --force            Overwrite an existing .env. Refuses by default, because
#                      regenerating APP_DATA_ENCRYPTION_KEY makes every
#                      encrypted column unreadable.
#
# Secret formats match exactly what the application validates at startup, and
# what infra/aws/foundation.yaml generates for the vendor's own environments:
#
#   APP_JWT_SECRET           64 hex chars. JwtSecretValidator requires >= 32
#                            bytes and an entropy floor; 64 clears both.
#   APP_DATA_ENCRYPTION_KEY  Base64 of exactly 32 random bytes.
#                            StartupSecurityValidator decodes it and checks the
#                            length. Note that foundation.yaml stores this as 64
#                            hex chars and converts at boot; here we write the
#                            Base64 form directly, which is what the app reads.

set -euo pipefail

cd "$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

PUBLIC_URL="https://localhost"
VERSION=""
LICENCE=""
FORCE=0

die()  { echo "error: $*" >&2; exit 1; }
info() { echo "  $*"; }

while [ $# -gt 0 ]; do
  case "$1" in
    --public-url) PUBLIC_URL="${2:?}"; shift 2 ;;
    --version)    VERSION="${2:?}";    shift 2 ;;
    --licence|--license) LICENCE="${2:?}"; shift 2 ;;
    --force)      FORCE=1;             shift ;;
    -h|--help)    sed -n '2,35p' "$0"; exit 0 ;;
    *) die "unknown argument: $1" ;;
  esac
done

# CorsConfig refuses localhost/127.0.0.1 as an origin under the prod profile,
# so an evaluation install at https://localhost has to opt in explicitly or the
# backend crash-loops before it ever serves a request.
case "$PUBLIC_URL" in
  *localhost*|*127.0.0.1*) ALLOW_LOCALHOST=true ;;
  *)                       ALLOW_LOCALHOST=false ;;
esac

command -v openssl >/dev/null || die "openssl is required"
command -v docker  >/dev/null || die "docker is required"

if [ -z "$VERSION" ]; then
  if [ -r VERSION ]; then
    VERSION="$(tr -d '[:space:]' < VERSION)"
  else
    die "no --version given and no VERSION file present.
       Pin the release you intend to run, e.g. --version 1.4.2
       A self-hosted installation must never track a moving tag: an unattended
       image change is an unattended schema migration."
  fi
fi
if [ "$VERSION" = "latest" ]; then die "--version latest is not permitted; pin a release tag"; fi

if [ -e .env ] && [ "$FORCE" -eq 0 ]; then
  die ".env already exists.
       Refusing to overwrite it: regenerating APP_DATA_ENCRYPTION_KEY would make
       every encrypted column (MFA secrets, SSO and webhook secrets, gateway
       tokens) permanently unreadable. Pass --force only if this installation
       has no data you intend to keep."
fi

echo ""
echo "AssetIQ self-hosted — bootstrap"
echo ""

# ── Secrets ──────────────────────────────────────────────────────────────────
# Written with a restrictive umask so .env is never briefly world-readable
# between creation and chmod.
umask 077

info "Generating secrets..."
JWT_SECRET="$(openssl rand -hex 32)"                 # 64 hex characters
DATA_KEY="$(openssl rand -base64 32 | tr -d '\n')"   # Base64 of 32 bytes
DB_PASSWORD="$(openssl rand -hex 24)"
REDIS_PASSWORD="$(openssl rand -hex 24)"
# Pre-generated so that turning on the optional MinIO profile later is a
# one-line change rather than another round of secret generation.
MINIO_USER="assetiq"
MINIO_PASSWORD="$(openssl rand -hex 24)"

# Fail loudly rather than write an .env the app will reject at boot.
[ "${#JWT_SECRET}" -eq 64 ] || die "generated JWT secret has the wrong length"
[ "$(printf '%s' "$DATA_KEY" | openssl base64 -d -A | wc -c | tr -d ' ')" -eq 32 ] \
  || die "generated data-encryption key is not 32 bytes"

cat > .env <<EOF
# AssetIQ self-hosted — generated by scripts/bootstrap.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
#
# THIS FILE CONTAINS SECRETS. It is mode 0600 and gitignored. Back it up
# somewhere you would keep a password database — losing APP_DATA_ENCRYPTION_KEY
# makes every encrypted column permanently unreadable, and no backup of the
# database can recover it.

# ── Release ──────────────────────────────────────────────────────────────────
ASSETIQ_VERSION=${VERSION}
ASSETIQ_REGISTRY=public.ecr.aws/assetiq

# ── Public address ───────────────────────────────────────────────────────────
APP_PUBLIC_URL=${PUBLIC_URL}
HTTP_PORT=80
HTTPS_PORT=443
# The prod profile rejects a localhost CORS origin outright. Set true only for
# an evaluation install reached at localhost; leave false for a real hostname.
APP_CORS_ALLOW_LOCALHOST=${ALLOW_LOCALHOST}

# ── Database ─────────────────────────────────────────────────────────────────
POSTGRES_DB=assetiq
POSTGRES_USER=assetiq
POSTGRES_PASSWORD=${DB_PASSWORD}

# ── Redis ────────────────────────────────────────────────────────────────────
REDIS_PASSWORD=${REDIS_PASSWORD}
REDIS_MAXMEMORY=256mb

# ── Application secrets ──────────────────────────────────────────────────────
APP_JWT_SECRET=${JWT_SECRET}
APP_JWT_EXPIRATION=900000
APP_REFRESH_TOKEN_LIFETIME=PT12H
APP_DATA_ENCRYPTION_KEY=${DATA_KEY}

# ── Licence ──────────────────────────────────────────────────────────────────
# Verified locally against the public key in the image. No licence server is
# contacted. An absent or lapsed key means free-tier quotas, never an outage.
APP_LICENSE_OFFLINE_ENABLED=true
APP_LICENSE_OFFLINE_KEY=${LICENCE}

# ── Email (optional) ─────────────────────────────────────────────────────────
# Without this, password reset and user invitation emails are not sent.
APP_EMAIL_ENABLED=false
SMTP_HOST=
SMTP_PORT=587
SMTP_USERNAME=
SMTP_PASSWORD=

# ── Object storage ───────────────────────────────────────────────────────────
# AssetIQ has NO local-disk storage backend. With this false, generated reports
# and imports live in the backend's JVM heap and are lost on every restart.
# Fine for evaluation, wrong for production.
#
# The bundled MinIO fixes it without leaving this host:
#   docker compose --profile minio up -d
#   docker compose exec minio mc alias set local http://127.0.0.1:9000 "\$MINIO_ROOT_USER" "\$MINIO_ROOT_PASSWORD"
#   docker compose exec minio mc mb --ignore-existing local/assetiq
# then set APP_STORAGE_S3_ENABLED=true and restart the backend.
APP_STORAGE_S3_ENABLED=false
APP_STORAGE_S3_BUCKET=assetiq
APP_STORAGE_S3_REGION=us-east-1
APP_STORAGE_S3_ENDPOINT=http://minio:9000
APP_STORAGE_S3_PATH_STYLE=true
AWS_ACCESS_KEY_ID=${MINIO_USER}
AWS_SECRET_ACCESS_KEY=${MINIO_PASSWORD}
MINIO_ROOT_USER=${MINIO_USER}
MINIO_ROOT_PASSWORD=${MINIO_PASSWORD}
EOF

chmod 600 .env
info ".env written (mode $(stat -f '%Lp' .env 2>/dev/null || stat -c '%a' .env))"

# ── TLS ──────────────────────────────────────────────────────────────────────
umask 022
mkdir -p nginx/certs
if [ -f nginx/certs/server.crt ] && [ -f nginx/certs/server.key ]; then
  info "TLS certificate already present — leaving it alone"
else
  HOSTNAME_ONLY="$(printf '%s' "$PUBLIC_URL" | sed -E 's#^https?://##; s#[:/].*$##')"
  info "Generating a self-signed certificate for ${HOSTNAME_ONLY}..."
  openssl req -x509 -newkey rsa:4096 -sha256 -days 365 -nodes \
    -keyout nginx/certs/server.key -out nginx/certs/server.crt \
    -subj "/CN=${HOSTNAME_ONLY}" \
    -addext "subjectAltName=DNS:${HOSTNAME_ONLY},DNS:localhost,IP:127.0.0.1" 2>/dev/null
  chmod 600 nginx/certs/server.key
  chmod 644 nginx/certs/server.crt
  info "Self-signed certificate written. Browsers will warn until you replace"
  info "it with a real one — put your full chain in nginx/certs/server.crt."
fi

cat <<EOF

Done. Next:

  docker compose pull
  docker compose up -d
  ./scripts/health-check.sh

Then open ${PUBLIC_URL}

EOF

if [ -z "$LICENCE" ]; then
  cat <<'EOF'
No licence key was supplied, so this installation will run on free-tier
quotas. Everything works; the limits are lower. Add your key to
APP_LICENSE_OFFLINE_KEY in .env and restart the backend when you have one.

EOF
fi
