#!/usr/bin/env bash
# setup-standalone.sh
#
# Interactive first-time setup wizard for AssetIQ Standalone.
# Run this from the assetiq-standalone/ directory before your first
# `docker compose up`.
#
# What it does:
#   1. Checks prerequisites (docker, docker compose, openssl)
#   2. Generates a self-signed TLS certificate (or skips if certs exist)
#   3. Writes a .env file using the backend's real production variable names
#   4. Prints a summary and the `docker compose up` command

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT_DIR"

BOLD="\033[1m"
GREEN="\033[0;32m"
YELLOW="\033[0;33m"
RED="\033[0;31m"
RESET="\033[0m"

# ── Helpers ───────────────────────────────────────────────────────────────────

info()    { echo -e "${GREEN}→${RESET} $*"; }
warn()    { echo -e "${YELLOW}⚠${RESET}  $*"; }
error()   { echo -e "${RED}✗${RESET}  $*"; exit 1; }
prompt()  { local var="$1"; local msg="$2"; local default="${3:-}"; 
            if [ -n "$default" ]; then read -rp "  $msg [$default]: " val; val="${val:-$default}";
            else read -rp "  $msg: " val; fi
            eval "$var=\"\$val\""; }
randHex() { openssl rand -hex "$1"; }
randBase64() { openssl rand -base64 "$1" | tr -d '\n'; }

echo ""
echo -e "${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
echo -e "${BOLD}   AssetIQ Standalone — First-Time Setup          ${RESET}"
echo -e "${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
echo ""

# ── 1. Prerequisites ──────────────────────────────────────────────────────────

info "Checking prerequisites…"

for cmd in docker openssl; do
  command -v "$cmd" &>/dev/null || error "$cmd is not installed. Please install it and re-run."
done

# docker compose v2 (plugin) or v1 (standalone)
if docker compose version &>/dev/null 2>&1; then
  COMPOSE_CMD="docker compose"
elif command -v docker-compose &>/dev/null; then
  COMPOSE_CMD="docker-compose"
else
  error "Docker Compose not found. Install Docker Desktop or the compose plugin."
fi

echo "  docker         ✓"
echo "  docker compose ✓"
echo "  openssl        ✓"
echo ""

# ── 2. TLS Certificate ────────────────────────────────────────────────────────

prompt DOMAIN "Domain name (e.g. assetiq.example.com)" "localhost"

if [ -f "nginx/certs/server.crt" ] && [ -f "nginx/certs/server.key" ]; then
  warn "TLS certificate already exists in nginx/certs/ — skipping."
else
  echo -e "${BOLD}TLS Certificate${RESET}"
  echo "  For local / intranet use, a self-signed certificate will be generated."
  echo "  For production, press Enter to skip and place your own cert in nginx/certs/."
  echo ""
  if [ -n "$DOMAIN" ]; then
    bash scripts/generate-self-signed-cert.sh "$DOMAIN"
  else
    warn "Skipping TLS cert. Place server.crt and server.key in nginx/certs/ before starting nginx."
  fi
fi
echo ""

# ── 3. Environment variables ──────────────────────────────────────────────────

echo -e "${BOLD}Database${RESET}"
prompt DB_PASS  "PostgreSQL password" "$(randHex 16)"
echo ""

echo -e "${BOLD}Security${RESET}"
JWT_SECRET_GEN=$(randHex 64)
DATA_ENCRYPTION_KEY_GEN=$(randBase64 32)

echo "  JWT and database encryption keys will be"
echo "  auto-generated. You can edit .env afterwards if needed."
echo ""

echo -e "${BOLD}License Key${RESET}"
echo "  After purchasing at portal.assetiq.io, paste your license key here."
echo "  You can also leave it blank and activate later in Settings → License."
prompt LICENSE_KEY "License key (or press Enter to skip)" ""
echo ""

echo -e "${BOLD}Paystack (optional)${RESET}"
echo "  Required only if you want cloud billing features in the standalone app."
prompt PAYSTACK_KEY "Paystack secret key (or press Enter to skip)" ""
echo ""

# Write .env
cat > .env << EOF
# Generated by setup-standalone.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# Edit this file to change any setting, then run: $COMPOSE_CMD up -d --force-recreate

POSTGRES_USER=assetiq
POSTGRES_PASSWORD=${DB_PASS}

APP_JWT_SECRET=${JWT_SECRET_GEN}
APP_JWT_EXPIRATION=900000
APP_REFRESH_TOKEN_LIFETIME=PT12H
APP_DATA_ENCRYPTION_KEY=${DATA_ENCRYPTION_KEY_GEN}

ASSETIQ_LICENSE_KEY=${LICENSE_KEY}
LICENSE_SERVER_URL=https://license.assetiq.io
STORAGE_TYPE=local
APP_CORS_ALLOWED_ORIGINS=https://${DOMAIN:-localhost}

PAYSTACK_SECRET_KEY=${PAYSTACK_KEY}
EOF

info ".env written."
echo ""

# ── 4. Summary ────────────────────────────────────────────────────────────────

echo -e "${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
echo -e "${GREEN}✅  Setup complete!${RESET}"
echo ""
echo "Start the stack:"
echo ""
echo -e "  ${BOLD}$COMPOSE_CMD -f docker-compose.standalone.yml up -d --build${RESET}"
echo ""
echo "Then open https://${DOMAIN:-localhost} in your browser."
if [ -z "$LICENSE_KEY" ]; then
  echo ""
  echo "You'll be prompted to activate your license key."
  echo "Get one at https://portal.assetiq.io"
fi
echo ""
echo -e "${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
