#!/usr/bin/env bash
# setup-standalone.sh
#
# Interactive first-time setup wizard for AssetIQ Standalone.
# Run this from the assetiq-standalone/ directory before your first
# `docker compose up`.
#
# What it does:
#   1. Checks prerequisites (docker, docker compose, openssl)
#   2. Generates RSA key pair for the license server
#   3. Generates a self-signed TLS certificate (or skips if certs exist)
#   4. Writes a .env file from your answers
#   5. Copies the RSA public key into the backend bundle
#   6. Prints a summary and the `docker compose up` command

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT_DIR"

BOLD="\033[1m"
GREEN="\033[0;32m"
YELLOW="\033[0;33m"
RED="\033[0;31m"
RESET="\033[0m"

# ── Helpers ───────────────────────────────────────────────────────────────────

info()    { echo -e "${GREEN}→${RESET} $*"; }
warn()    { echo -e "${YELLOW}⚠${RESET}  $*"; }
error()   { echo -e "${RED}✗${RESET}  $*"; exit 1; }
prompt()  { local var="$1"; local msg="$2"; local default="${3:-}"; 
            if [ -n "$default" ]; then read -rp "  $msg [$default]: " val; val="${val:-$default}";
            else read -rp "  $msg: " val; fi
            eval "$var=\"\$val\""; }
randHex() { openssl rand -hex "$1"; }

echo ""
echo -e "${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
echo -e "${BOLD}   AssetIQ Standalone — First-Time Setup          ${RESET}"
echo -e "${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
echo ""

# ── 1. Prerequisites ──────────────────────────────────────────────────────────

info "Checking prerequisites…"

for cmd in docker openssl; do
  command -v "$cmd" &>/dev/null || error "$cmd is not installed. Please install it and re-run."
done

# docker compose v2 (plugin) or v1 (standalone)
if docker compose version &>/dev/null 2>&1; then
  COMPOSE_CMD="docker compose"
elif command -v docker-compose &>/dev/null; then
  COMPOSE_CMD="docker-compose"
else
  error "Docker Compose not found. Install Docker Desktop or the compose plugin."
fi

echo "  docker         ✓"
echo "  docker compose ✓"
echo "  openssl        ✓"
echo ""

# ── 2. RSA Keys ───────────────────────────────────────────────────────────────

if [ -f "keys/private.pem" ] && [ -f "keys/public.pem" ]; then
  warn "RSA keys already exist in keys/ — skipping generation."
else
  info "Generating RSA-2048 key pair for the License Server…"
  bash scripts/generate-rsa-keys.sh
fi
echo ""

# ── 3. TLS Certificate ────────────────────────────────────────────────────────

if [ -f "nginx/certs/server.crt" ] && [ -f "nginx/certs/server.key" ]; then
  warn "TLS certificate already exists in nginx/certs/ — skipping."
else
  echo -e "${BOLD}TLS Certificate${RESET}"
  echo "  For local / intranet use, a self-signed certificate will be generated."
  echo "  For production, press Enter to skip and place your own cert in nginx/certs/."
  echo ""
  prompt DOMAIN "Domain name (e.g. assetiq.example.com)" "localhost"
  if [ -n "$DOMAIN" ]; then
    bash scripts/generate-self-signed-cert.sh "$DOMAIN"
  else
    warn "Skipping TLS cert. Place server.crt and server.key in nginx/certs/ before starting nginx."
  fi
fi
echo ""

# ── 4. Environment variables ──────────────────────────────────────────────────

echo -e "${BOLD}Database${RESET}"
prompt DB_PASS  "PostgreSQL password" "$(randHex 16)"
echo ""

echo -e "${BOLD}Security${RESET}"
JWT_SECRET_GEN=$(randHex 64)
ADMIN_KEY_GEN=$(randHex 32)
CHECKOUT_SECRET_GEN=$(randHex 32)

echo "  JWT secret, License admin key, and Checkout session secret will be"
echo "  auto-generated. You can edit .env afterwards if needed."
echo ""

echo -e "${BOLD}License Key${RESET}"
echo "  After purchasing at portal.assetiq.io, paste your license key here."
echo "  You can also leave it blank and activate later in Settings → License."
prompt LICENSE_KEY "License key (or press Enter to skip)" ""
echo ""

echo -e "${BOLD}Paystack (optional)${RESET}"
echo "  Required only if you want cloud billing features in the standalone app."
prompt PAYSTACK_KEY "Paystack secret key (or press Enter to skip)" ""
echo ""

# Write .env
cat > .env << EOF
# Generated by setup-standalone.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# Edit this file to change any setting, then run: $COMPOSE_CMD up -d --force-recreate

POSTGRES_USER=assetiq
POSTGRES_PASSWORD=${DB_PASS}

JWT_SECRET=${JWT_SECRET_GEN}
JWT_EXPIRATION_MS=86400000

ASSETIQ_LICENSE_KEY=${LICENSE_KEY}
STORAGE_TYPE=local

LICENSE_ADMIN_API_KEY=${ADMIN_KEY_GEN}
LICENSE_RATE_LIMIT_RPM=30
LICENSE_ABUSE_MAX_FINGERPRINTS=2

PAYSTACK_SECRET_KEY=${PAYSTACK_KEY}

CHECKOUT_SESSION_SECRET=${CHECKOUT_SECRET_GEN}
EOF

info ".env written."
echo ""

# ── 5. Copy public key into backend bundle ────────────────────────────────────

BACKEND_KEY_DIR="../../Enterprise-Asset-Manager/src/main/resources/license"
if [ -d "../../Enterprise-Asset-Manager" ]; then
  mkdir -p "$BACKEND_KEY_DIR"
  cp keys/public.pem "$BACKEND_KEY_DIR/public.pem"
  info "Public key copied to $BACKEND_KEY_DIR/public.pem"
else
  warn "Backend source not found at ../../Enterprise-Asset-Manager."
  warn "Manually copy keys/public.pem to:"
  warn "  Enterprise-Asset-Manager/src/main/resources/license/public.pem"
fi
echo ""

# ── 6. Summary ────────────────────────────────────────────────────────────────

echo -e "${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
echo -e "${GREEN}✅  Setup complete!${RESET}"
echo ""
echo "Start the stack:"
echo ""
echo -e "  ${BOLD}$COMPOSE_CMD -f docker-compose.standalone.yml up -d --build${RESET}"
echo ""
echo "Then open https://${DOMAIN:-localhost} in your browser."
if [ -z "$LICENSE_KEY" ]; then
  echo ""
  echo "You'll be prompted to activate your license key."
  echo "Get one at https://portal.assetiq.io"
fi
echo ""
echo -e "${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
