package com.assetiq.db;

import org.flywaydb.core.Flyway;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.testcontainers.containers.PostgreSQLContainer;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.UUID;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Proves that permanently deleting a tenant really does take its data with it.
 *
 * <p>This has to run against real PostgreSQL with the Flyway chain applied. The main
 * test profile uses H2 with {@code ddl-auto=create-drop} and Flyway disabled, so its
 * foreign keys are generated by Hibernate and carry no {@code ON DELETE CASCADE} —
 * the migrations are where those live. A purge test on H2 would prove nothing about
 * production, and in fact fails there for reasons that do not apply in production.
 *
 * <p>Guards a real bug found while building account closure: the service originally
 * called {@code organisationRepository.delete(entity)}, and because Organisation maps
 * departments/users/assets/roles with {@code CascadeType.ALL}, Hibernate issued its own
 * DELETEs for those four collections in an order that ignored the other ~90
 * organisation-scoped tables. Removing app_user first tripped
 * {@code audit_event.actor_id} and the purge died partway through, leaving a
 * half-deleted tenant. The fix hands the whole teardown to the database.
 */
@Testcontainers
@DisplayName("Account purge cascade")
class AccountPurgeCascadeTest {

    @Container
    @SuppressWarnings("resource")
    static final PostgreSQLContainer<?> postgres =
            new PostgreSQLContainer<>("postgres:16-alpine")
                    .withDatabaseName("purge_cascade")
                    .withUsername("postgres")
                    .withPassword("postgres");

    @BeforeAll
    static void migrate() {
        Flyway.configure()
                .dataSource(postgres.getJdbcUrl(), postgres.getUsername(), postgres.getPassword())
                .locations("classpath:db/migration")
                .load()
                .migrate();
    }

    @Test
    @DisplayName("deleting an organisation removes its users and audit trail with it")
    void deletingOrganisationCascadesToDependentRows() throws Exception {
        UUID orgId = UUID.randomUUID();
        UUID userId = UUID.randomUUID();
        UUID auditId = UUID.randomUUID();

        try (Connection conn = DriverManager.getConnection(
                postgres.getJdbcUrl(), postgres.getUsername(), postgres.getPassword())) {

            insertOrganisation(conn, orgId);
            insertUser(conn, userId, orgId);
            insertAuditEvent(conn, auditId, orgId, userId);

            assertEquals(1, count(conn, "organisation", orgId));
            assertEquals(1, count(conn, "app_user", userId));
            assertEquals(1, count(conn, "audit_event", auditId));

            // Exactly what AccountLifecycleService.purgeExpiredAccounts issues.
            try (PreparedStatement ps =
                         conn.prepareStatement("DELETE FROM organisation WHERE id = ?")) {
                ps.setObject(1, orgId);
                assertEquals(1, ps.executeUpdate(), "the organisation row should be deleted");
            }

            assertEquals(0, count(conn, "organisation", orgId));
            assertEquals(0, count(conn, "app_user", userId),
                    "users must be removed by the cascade, not left orphaned");
            assertEquals(0, count(conn, "audit_event", auditId),
                    "the audit trail belongs to the tenant and must go with it — "
                            + "an audit_event referencing a deleted actor is what broke the "
                            + "original JPA-based purge");
        }
    }

    @Test
    @DisplayName("every organisation_id foreign key cascades")
    void allOrganisationForeignKeysCascade() throws Exception {
        try (Connection conn = DriverManager.getConnection(
                postgres.getJdbcUrl(), postgres.getUsername(), postgres.getPassword());
             Statement st = conn.createStatement()) {

            // The purge depends on this being true of *every* table, including ones added
            // later. A new table with a non-cascading organisation_id would leave tenants
            // undeletable, and the failure would only appear 30 days after someone closed
            // an account.
            ResultSet rs = st.executeQuery("""
                    SELECT con.conrelid::regclass::text AS child_table, con.confdeltype
                    FROM pg_constraint con
                    JOIN pg_class ref ON ref.oid = con.confrelid
                    WHERE con.contype = 'f'
                      AND ref.relname = 'organisation'
                      AND con.confdeltype <> 'c'
                    """);

            StringBuilder offenders = new StringBuilder();
            while (rs.next()) {
                offenders.append("\n  ").append(rs.getString("child_table"))
                        .append(" (confdeltype=").append(rs.getString("confdeltype")).append(")");
            }

            assertTrue(offenders.isEmpty(),
                    "These tables reference organisation without ON DELETE CASCADE, so a "
                            + "tenant purge would fail on them:" + offenders);
        }
    }

    // ── Fixtures ──────────────────────────────────────────────────────────────

    private void insertOrganisation(Connection conn, UUID id) throws Exception {
        try (PreparedStatement ps = conn.prepareStatement(
                "INSERT INTO organisation (id, name, contact_email, created_at, updated_at) "
                        + "VALUES (?, ?, ?, NOW(), NOW())")) {
            ps.setObject(1, id);
            ps.setString(2, "Purge Test Org " + id.toString().substring(0, 8));
            ps.setString(3, "purge-" + id.toString().substring(0, 8) + "@example.com");
            ps.executeUpdate();
        }
    }

    private void insertUser(Connection conn, UUID id, UUID orgId) throws Exception {
        try (PreparedStatement ps = conn.prepareStatement(
                "INSERT INTO app_user (id, first_name, last_name, email, password_hash, "
                        + "employee_id, organisation_id, created_at, updated_at) "
                        + "VALUES (?, ?, ?, ?, ?, ?, ?, NOW(), NOW())")) {
            ps.setObject(1, id);
            ps.setString(2, "Purge");
            ps.setString(3, "User");
            ps.setString(4, "purge-user-" + id.toString().substring(0, 8) + "@example.com");
            ps.setString(5, "not-a-real-hash");
            ps.setString(6, "EMP-" + id.toString().substring(0, 8));
            ps.setObject(7, orgId);
            ps.executeUpdate();
        }
    }

    private void insertAuditEvent(Connection conn, UUID id, UUID orgId, UUID actorId) throws Exception {
        try (PreparedStatement ps = conn.prepareStatement(
                "INSERT INTO audit_event (id, organisation_id, actor_id, event_type, method, path, "
                        + "response_status, success, created_at, updated_at) "
                        + "VALUES (?, ?, ?, 'API_REQUEST', 'GET', '/api/v1/assets', 200, TRUE, NOW(), NOW())")) {
            ps.setObject(1, id);
            ps.setObject(2, orgId);
            ps.setObject(3, actorId);
            ps.executeUpdate();
        }
    }

    private int count(Connection conn, String table, UUID id) throws Exception {
        try (PreparedStatement ps =
                     conn.prepareStatement("SELECT COUNT(*) FROM " + table + " WHERE id = ?")) {
            ps.setObject(1, id);
            try (ResultSet rs = ps.executeQuery()) {
                rs.next();
                return rs.getInt(1);
            }
        }
    }
}
