package com.assetiq.dto;

import com.assetiq.enums.AuditDiscrepancyType;
import com.assetiq.enums.AuditItemStatus;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Data;

import java.time.Instant;
import java.util.UUID;

/**
 * One line of an audit count sheet, as the client sees it.
 *
 * <p>Read-only throughout: items are generated by the server from the assets in
 * scope, and changed only through the verify and discrepancy endpoints, never by
 * posting this shape back.
 */
@Data
public class AuditItemDto {

    private UUID id;

    private UUID auditId;

    private UUID assetId;

    /** The asset's tag — what the auditor reads off the label. */
    private String assetTag;

    private String assetName;

    private AuditItemStatus status;

    private String expectedLocation;

    private String actualLocation;

    private String condition;

    private Boolean discrepancyFlag;

    private AuditDiscrepancyType discrepancyType;

    private String discrepancyReason;

    private String remarks;

    private Instant verifiedAt;

    /** Display name of whoever verified or flagged the item. */
    @JsonProperty(access = JsonProperty.Access.READ_ONLY)
    private String verifiedByName;

    private Instant createdAt;

    private Instant updatedAt;
}
