-- Asset tags used to be generated by reading every existing PREFIX-* tag and
-- adding one. Two saves that overlapped read the same maximum and produced the
-- same tag; one then failed on uq_asset_org_tag_live (V46) with a misleading
-- "same name already exists" message. A counter per organisation and prefix
-- hands out numbers atomically instead (INSERT ... ON CONFLICT DO UPDATE
-- RETURNING), so concurrent creates serialise on the counter row for the
-- moment it takes to claim a number.
--
-- Expand-only: a new table. No backfill — each counter is seeded on first use
-- from the highest tag that already exists for its prefix, so existing tags are
-- never reused and no asset row is touched.
--
-- Pre-check (expects 0 rows; a live duplicate would already break V46's index):
--   SELECT organisation_id, asset_tag, COUNT(*)
--     FROM asset
--    WHERE deleted_at IS NULL AND asset_tag IS NOT NULL
--    GROUP BY organisation_id, asset_tag
--   HAVING COUNT(*) > 1;
CREATE TABLE IF NOT EXISTS asset_tag_sequence (
    organisation_id UUID         NOT NULL,
    prefix          VARCHAR(64)  NOT NULL,
    next_number     BIGINT       NOT NULL,
    CONSTRAINT pk_asset_tag_sequence PRIMARY KEY (organisation_id, prefix),
    CONSTRAINT fk_asset_tag_sequence_org FOREIGN KEY (organisation_id)
        REFERENCES organisation (id) ON DELETE CASCADE
);
