-- V61: one live insight per asset and type, enforced by the database.
--
-- PredictiveMaintenanceServiceImpl "upserts" by deleting the unresolved insight
-- for an asset+type and inserting a fresh one. With nothing but application code
-- holding that invariant, two refreshes running at once — the nightly job and a
-- user pressing Regenerate — can both delete and then both insert, leaving two
-- unresolved insights for the same asset and type. The dashboard would then
-- double-count, and resolving one would leave its twin behind.
--
-- The index makes the second writer fail instead of silently duplicating. The
-- nightly job treats that as "a concurrent refresh already produced an
-- equivalent set" and moves on; the manual endpoint surfaces it as a 409.
--
-- Scope of the index: only live, unresolved, asset-attached rows. Resolved rows
-- are history and must be allowed to accumulate — an asset can go overdue,
-- be resolved, and go overdue again. Soft-deleted rows are likewise exempt.
--
-- The dedupe below removes duplicate *derived* rows only. Every row it deletes
-- is regenerated by the next refresh from the assets and maintenance records it
-- was computed from; nothing a user authored is touched.

DELETE FROM predictive_insight p
USING predictive_insight q
WHERE  p.asset_id IS NOT NULL
  AND  p.resolved = FALSE AND p.deleted_at IS NULL
  AND  q.resolved = FALSE AND q.deleted_at IS NULL
  AND  p.asset_id     = q.asset_id
  AND  p.insight_type = q.insight_type
  AND  (p.created_at, p.id) < (q.created_at, q.id);

CREATE UNIQUE INDEX IF NOT EXISTS uq_predictive_insight_live
    ON predictive_insight (asset_id, insight_type)
    WHERE resolved = FALSE AND deleted_at IS NULL AND asset_id IS NOT NULL;
