package com.assetiq.assets;

import com.assetiq.BaseIntegrationTest;
import com.assetiq.models.Organisation;
import com.assetiq.repositories.OrganisationRepository;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;

import java.util.List;
import java.util.Set;
import java.util.UUID;
import java.util.concurrent.Callable;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;
import java.util.stream.IntStream;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Asset tags used to be generated by reading the highest existing one and adding
 * one, so two saves at the same moment produced the same tag and one of them
 * failed on uq_asset_org_tag_live. The counter (V54) hands out numbers one at a
 * time however many callers ask at once.
 */
@DisplayName("Concurrent asset-tag generation never repeats a number")
class AssetTagAllocatorConcurrencyTest extends BaseIntegrationTest {

    @Autowired AssetTagAllocator allocator;
    @Autowired OrganisationRepository organisationRepository;

    @Test
    void twentyCallersAtOnceGetTwentyDistinctNumbers() throws Exception {
        Organisation org = new Organisation();
        org.setName("Tag allocator " + UUID.randomUUID());
        Organisation saved = organisationRepository.save(org);

        int callers = 20;
        try (ExecutorService pool = Executors.newFixedThreadPool(callers)) {
            List<Callable<Long>> claims = IntStream.range(0, callers)
                    .<Callable<Long>>mapToObj(i -> () -> allocator.claimNext(saved.getId(), "LAP", 4L))
                    .toList();
            List<Future<Long>> futures = pool.invokeAll(claims);
            Set<Long> numbers = new java.util.HashSet<>();
            for (Future<Long> f : futures) {
                numbers.add(f.get());
            }
            // Seeded from the highest tag in use (4), so 5..24 with no repeats.
            assertThat(numbers).hasSize(callers);
            assertThat(numbers).allMatch(n -> n > 4 && n <= 4 + callers);
        }
    }

    @Test
    void separatePrefixesAndOrganisationsCountIndependently() {
        Organisation a = organisationRepository.save(named("Tag org A"));
        Organisation b = organisationRepository.save(named("Tag org B"));

        assertThat(allocator.claimNext(a.getId(), "LAP", 0L)).isEqualTo(1L);
        assertThat(allocator.claimNext(a.getId(), "MON", 0L)).isEqualTo(1L);
        assertThat(allocator.claimNext(b.getId(), "LAP", 0L)).isEqualTo(1L);
        assertThat(allocator.claimNext(a.getId(), "LAP", 0L)).isEqualTo(2L);
    }

    private Organisation named(String name) {
        Organisation org = new Organisation();
        org.setName(name + " " + UUID.randomUUID());
        return org;
    }
}
